#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme layer.

    # colorscheme = "gruvbox"
    # colorscheme = "onedark"
    # colorscheme = "material"
    # colorscheme = "NeoSolarized"
    # colorscheme = "hybrid"
    # colorscheme = "molokai"
    # colorscheme = "srcery"
    # colorscheme = "jellybeans"
    colorscheme = "SpaceVim"

    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4

    # 在标签栏上展示文件类型的图标
    enable_tabline_filetype_icon = true

    # 文字显示当前模式:INSERT/NORMAL...
    enable_statusline_mode = true

    # 缩进默认使用4个空格
    default_indent = 4

    enable_key_frequency = true

    # 文件管理器使用defx
    filemanager = "defx"

    # 代码片段引擎使用ultisnips
    snippet_engine = "ultisnips"

    # 高亮当前列
    enable_cursorcolumn = true

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "lang#go"

[[layers]]
    name = "checkers"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "fzf"

[[layers]]
    name = "git"

[[layers]]
    name = "tools"

[[layers]]
    name = "ui"
